### PR TITLE
Fix pathname#write

### LINKED ISSUE #381: Undefined method Pathname#write
Pathname inherits some FileUtils and File methods, like `#write`.

However in the fake version the method isn't available.

### PR DESCRIPTION
**Pull request by iainbryson**
[ Fix #381 ]

`pathname#write`'s signature is wrong; it has the path as first argument which is absurd since the object itself is the path.

According to [ruby-doc](https://ruby-doc.org/stdlib-2.1.3/libdoc/pathname/rdoc/Pathname.html#method-i-write) the arguments should be:

> write(string, [offset] ) => fixnum
> write(string, [offset], open_args ) => fixnum

This PR changes the code and test to conform to that.

### CODE REVIEW

File: lib/fakefs/pathname.rb [hunk 1]
```diff
@@ -787,9 +787,12 @@ def split
     end
 
     # See <tt>File.write</tt>. Returns the number of bytes written.
-    def write(path, data)
-      File.open(path, 'wb') do |file|
-        return file.write(data)
+    def write(string, *args)
+      offset = args[0]
+      open_args = args[1]
```
Comment (grosser) [inline lib/fakefs/pathname.rb]: got some tests for offset/args too ?

**Comment by grosser** [comment]
meh .. good enough :)

**Comment by grosser** [comment]
0.20.1
