### PR TITLE
Fix: atime/mtime of copied entities in cp_r based on preserve option

### LINKED ISSUE #518: cp_r does not respect preserve parameter
`cp_r` is supposed to only preserve file times (atime and mtime) if the `preserve` option is `true`. FakeFS implementation currently _always_ preserves file times.

I am willing to PR. Are you okay with adding Timecop as a dependency? Otherwise I will have to `sleep` in tests which will make them massively slower.

### PR DESCRIPTION
**Pull request by BadIdeaException**
Fixes #518.

### CODE REVIEW

File: lib/fakefs/fileutils.rb [hunk 1]
```diff
@@ -305,5 +315,17 @@ def uptodate?(new, old_list)
       end
       true
     end
+
+    # Walks through the file system hierarchy recursively, starting from the given entry,
+    # and calls the given block with it.
+    # If no block is given, returns an Enumerator.                                                                                   
+    private def walk(entry, &block)
```
Comment (grosser) [inline lib/fakefs/fileutils.rb:322]: maybe make it a bit less generic
```suggestion
    private def walk_hierarchy(entry, &block) 
```

File: lib/fakefs/fileutils.rb [hunk 2]
```diff
@@ -305,5 +315,17 @@ def uptodate?(new, old_list)
       end
       true
     end
+
+    # Walks through the file system hierarchy recursively, starting from the given entry,
+    # and calls the given block with it.
+    # If no block is given, returns an Enumerator.                                                                                   
+    private def walk(entry, &block) 
+      return to_enum(__method__, entry) unless block_given?
```
Comment (grosser) [inline lib/fakefs/fileutils.rb:323]: why do we need this ?

File: lib/fakefs/fileutils.rb [hunk 3]
```diff
@@ -160,18 +161,27 @@ def cp_r(src, dest, options = {})
...
         raise Errno::ENOENT, dest.to_s if !new_dir && !FileSystem.find(dest.to_s + '/../')
 
+        update_times = proc { |f| f.atime = f.mtime = Time.now }
         # This last bit is a total abuse and should be thought hard
         # about and cleaned up.
         if new_dir
-          if src.to_s[-2..-1] == '/.'
-            dir.entries.each { |f| new_dir[f.name] = f.clone(new_dir) }
+          if src.to_s[-2..-1] == '/.'            
+            dir.entries.each { |f|
```
Comment (grosser) [inline lib/fakefs/fileutils.rb:169]: use do/end for multiline

File: lib/fakefs/fileutils.rb (hunk 2 above)
Comment (grosser) [reply lib/fakefs/fileutils.rb:322]: more asking why we need the unless block_given since I though we always pass a block

File: lib/fakefs/fileutils.rb [hunk 4]
```diff
@@ -160,18 +161,27 @@ def cp_r(src, dest, options = {})
...
+            dir.entries.each { |f| 
+              copy = f.clone(new_dir)
+              walk(copy, &update_times) unless options[:preserve]
+              new_dir[f.name] = copy              
+            }
           else
-            new_dir[dir.name] = dir.entry.clone(new_dir)
+            copy = dir.entry.clone(new_dir)
+            walk(copy, &update_times) unless options[:preserve]
+            new_dir[dir.name] = copy
```
[the remark this answers is not in the document]
Comment (grosser) [reply lib/fakefs/fileutils.rb]: yeah just leave them then, on first view looked very similar

File: lib/fakefs/fileutils.rb (hunk 2 above)
Comment (BadIdeaException) [reply lib/fakefs/fileutils.rb:324]: Technically true, but this way seemed more in keeping with how other Ruby enumerators behave.

**Comment by grosser** [comment]
just random error
